spring.application.name=backend

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/eventsphere
spring.datasource.username=eventsphere
spring.datasource.password=eventsphere

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration